(autoload 'tinymacro-restore                    "tinymacro" "" t)
(autoload 'tinymacro-macro-info                 "tinymacro" "" t)
(autoload 'tinymacro-end-kbd-macro-and-assign   "tinymacro" "" t)
(autoload 'tinymacro-install-default-keybindings "tinymacro" "" t)
(autoload 'tinymacro-assign                     "tinymacro" "" t)
(provide 'tinymacro-epackage-install)
